server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # 支持 Vue 路由的配置
    location / {
        try_files $uri /index.html;
    }

    # 处理静态资源
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|otf|svg|map)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    # 错误页
    error_page 404 /index.html;
}
