// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CgDropDownSearchSrcAccountTypeField: typeof import('./../src/components/CgDropDownSearch/src/AccountTypeField.tsx')['default']
    CgExportExcelSrcExcelExport: typeof import('./../src/components/CgExportExcel/src/ExcelExport.tsx')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ReAnimateSelectorSrc: typeof import('./../src/components/ReAnimateSelector/src/index.vue')['default']
    ReAuthSrcAuth: typeof import('./../src/components/ReAuth/src/auth.tsx')['default']
    ReBarcodeSrc: typeof import('./../src/components/ReBarcode/src/index.vue')['default']
    ReCountToSrcNormal: typeof import('./../src/components/ReCountTo/src/normal/index.tsx')['default']
    ReCountToSrcRebound: typeof import('./../src/components/ReCountTo/src/rebound/index.tsx')['default']
    ReCropperPreviewSrc: typeof import('./../src/components/ReCropperPreview/src/index.vue')['default']
    ReCropperSrc: typeof import('./../src/components/ReCropper/src/index.tsx')['default']
    ReDialog: typeof import('./../src/components/ReDialog/index.vue')['default']
    ReFloatButtonSrc: typeof import('./../src/components/ReFloatButton/src/index.vue')['default']
    ReFlopSrc: typeof import('./../src/components/ReFlop/src/index.vue')['default']
    ReFlopSrcFilpper: typeof import('./../src/components/ReFlop/src/filpper.tsx')['default']
    ReFlowChartSrcControl: typeof import('./../src/components/ReFlowChart/src/Control.vue')['default']
    ReFlowChartSrcDataDialog: typeof import('./../src/components/ReFlowChart/src/DataDialog.vue')['default']
    ReFlowChartSrcNodePanel: typeof import('./../src/components/ReFlowChart/src/NodePanel.vue')['default']
    ReIconSrcSelect: typeof import('./../src/components/ReIcon/src/Select.vue')['default']
    ReImageVerifySrc: typeof import('./../src/components/ReImageVerify/src/index.vue')['default']
    ReMapSrcAmap: typeof import('./../src/components/ReMap/src/Amap.vue')['default']
    RePermsSrcPerms: typeof import('./../src/components/RePerms/src/perms.tsx')['default']
    RePureTableBarSrcBar: typeof import('./../src/components/RePureTableBar/src/bar.tsx')['default']
    ReQrcodeSrc: typeof import('./../src/components/ReQrcode/src/index.tsx')['default']
    ReSeamlessScrollSrc: typeof import('./../src/components/ReSeamlessScroll/src/index.vue')['default']
    ReSegmentedSrc: typeof import('./../src/components/ReSegmented/src/index.tsx')['default']
    ReSelectorSrc: typeof import('./../src/components/ReSelector/src/index.tsx')['default']
    ReSplitPane: typeof import('./../src/components/ReSplitPane/index.tsx')['default']
    ReSplitPaneResizer: typeof import('./../src/components/ReSplitPane/resizer.tsx')['default']
    ReTextSrc: typeof import('./../src/components/ReText/src/index.vue')['default']
    ReTypeitSrc: typeof import('./../src/components/ReTypeit/src/index.tsx')['default']
    ReVxeTableBarSrcBar: typeof import('./../src/components/ReVxeTableBar/src/bar.tsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
